%**************************************************************************
% Purpose: Default parameters
% -------  
% 
% Date: 27/01/2008
% Quoc Tran Dinh, OPTEC-SCD, ESAT, KULeuven, Belgium.
%
% This program is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
% 
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with this program.  If not, see <http://www.gnu.org/licenses/>.
%
%**************************************************************************
function options = cm_defopt( )

% generate default structure
options = struct( ...
      'started', 0, ...
      'maxiter', 30, ...
      'TolX', 1e-6, ... 
      'TolF', 1e-6, ...
      'maxLsiter', 10, ...
      'alphamax', 1, ...
      'alphamin', 1e-4, ...
      'c1par', 1e-4, ...
      'beta', 0.95, ...
      'mufactor', 1.2, ...
      'muincrease', 5, ...
      'rho', 0.5, ...
      'mu0', 1e0, ...
      'isplot', 'off', ...  % 'iter'
      'isprint', 'iter', ...
      'solver', 'sedumi', ...
      'verbose', 0, ...
      'isvisual', 'pvpatadvatr', ... %'pvpatadvatrm'
      'nsize', 50, ...
      'prob', 1, ...
      'amin', [-50; -10], ...
      'amax', [10; 10], ...
      'bmin', -1, ...
      'bmax', 1, ...
      'rhoa', 0, 'rhou', 0, 'rhoe', 0 );

%**************************************************************************
% End of this file
%**************************************************************************
