function [S] = computeGridHalton(n,b1,b2)
% Input: the number of samples n, two prime numbers b1 and b2
% Output: a Halton sequence of n samples inside [0, 1]2 generated by the two prime numbers b1 and b2

if ~(isprime(b1) && isprime(b2))
    error('b1 and b2 must be prime')
end

S = computeHaltonSequence(n,b1);
S = [S computeHaltonSequence(n,b2)];


plot(S(:,1),S(:,2),'o')
axis([0 1 0 1])