% ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
% FUNCTION: disp_msg - display message for "scp-cvx" solver
% Date: 20-06-2009
% Create by: Quoc Tran Dinh, ESAT/SCD and OPTEC, KULeuven, Belgium.
% Supervisor: Prof. Moritz Diehl.
% ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
function msg = disp_msg( opt, isdisp, pinfo, dinfo )

nsz = 92;
switch( opt )
    % the provided problem is only convex.
    case 'only_convex',
        outMsg = sprintf( '\n%s\n%s%s%s\n%s\n%s\n%s\n%s\n%s', ...
             repmat( '=', 1, nsz ), ...
             repmat( char(32), 1, nsz/2-7 ), 'SCP-CVX INTERFACE', ...
             repmat( char(32), 1, nsz/2-7 ), ...
             '+ SCP-CVX is an interface using CVX package', ...
             '+ For CVX software, see: http://www.stanford.edu/~boyd/cvx (M.Grant, S. Boyd)', ...
             '+ The provided problem is convex, CVX solver is called!', ...
             '+ VERSION: Pre-alpha, available at http://www.kuleuven.be/optec/v2/index.php/software', ...
             repmat( '=', 1, nsz ) );
         
         if isdisp, disp( outMsg ); end
         
    case 'info',
        outMsg = sprintf( '\n%s\n%s%s%s\n%s\n%s\n%s%s\n%s\n%s\n%s\n%s\n%s\n%s', ...
             repmat( '=', 1, nsz ), ...
             repmat( char(32), 1, nsz/2-7 ), 'SCP-CVX INTERFACE', ...
             repmat( char(32), 1, nsz/2-7 ), ...
             '+ SCP-CVX is an interface using CVX package', ...
             '+ For CVX software, see: http://www.stanford.edu/~boyd/cvx (M.Grant, S. Boyd)', ...
             '+ PURPOSE: Solves the following nonconvex optimization', ...
             ' problem:', ...
             [ repmat( char(32), 1, nsz/2-12 ), 'minimize f(x) := c', ...
               char(39), '*x' ], ...
             [ repmat( char(32), 1, nsz/2-12 ), 'subject to: g(x) = 0, ', ...
               'x in C' ], ...  
             [ '         where: c in R^n, g - nonlinear (g : R^n -> R^m), ', ... '
               'C - convex set in R^n'], ...
             '+ METHOD: Sequential Convex Programming (SCP)', ...
             '+ VERSION: Pre-alpha, available at http://www.kuleuven.be/optec/v2/index.php/software', ...
             repmat( '=', 1, nsz ) );
                 
        if isdisp, disp( outMsg ); end
        
    case 'header',
        outMsg = sprintf( '%s\n%s%s%s\n%s', repmat( '-', 1, nsz ), ... 
                 '   Iter F-count  feasibleGap     ', ...
                 'normOfSDir      stepSize      ', ...
                 'DirDeriv    SubProb/LsStatus ', ...
                 repmat( '-', 1, nsz ) );
        if isdisp, disp( outMsg ); end
        
    case 'done',
        outMsg = sprintf( '%s\n%s%s\n%s%s\n%s', ...
                repmat('-', 1, nsz), ...
                'Optimization terminated: ', ...
                ' first order optimality measure less ', ...
                'than WSPARS.TolFun and maximum constraint', ...
                ' violation is less than WSPARS.TolCon', ...
                repmat('-', 1, nsz) );
        if isdisp,  disp( outMsg ); end
        
    case 'maxiter',
        outMsg = sprintf( '%s\n%s\n%s\n%s', ...
                repmat( '-', 1, nsz ), ...
                'Maximum number of iterations exceeded;', ...
                'Increase WSPARS.maxSCPIters', ...
                repmat( '-', 1, nsz ));
        if isdisp, disp( outMsg ); end
        
    case 'maxfncount',
        outMsg = sprintf( '%s\n%s%s\n%s\n%s', ...
                    repmat( '-', 1, nsz ), ...
                    'Maximum number of function', ...
                    ' evaluations exceeded;', ...
                    'Increase WSPARS.maxFunEvals', ...
                    repmat( '-', 1, nsz ));
        if isdisp, disp( outMsg ); end
    
    case 'result',
        if nargin > 2
            outMsg = sprintf( '%s\n%s%6.6f\n%s%d\n%s%d\n%s%3.3f\n%s%s\n%s', ...
                repmat( '-', 1, nsz ), ...
                ' + Optimal value:  ', pinfo.results.fsol, ...
                ' + Number of iterations: ', pinfo.niter, ...
                ' + Number of function evaluations: ', pinfo.fncount, ...
                ' + CPU Time: ', pinfo.cputime, ...
                ' + Status: ', pinfo.status, ...
                repmat( '=', 1, nsz ) );
            if isdisp, disp( outMsg ); end
        end
    otherwise
        outMsg = '';
end

if nargout > 0, msg = outMsg; end

% ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
% Copyright 2009 Quoc Tran Dinh and Moritz Diehl.
% See the file COPYING.txt for full copyright information.
% The command 'scp_where' will show where this file is located.
% ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++