% ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
% FUNCTION: optionfields - return all the workspace options.
% Date: 18/06/2009
% Create by: Quoc Tran Dinh, ESAT/SCD and OPTEC, KULeuven, Belgium.
% Supervisor: Prof. Moritz Diehl.
% ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
function [ fieldname, fieldtype, fieldrange ] = optionfields( )

% declare the field name of the optional variables
fieldname = { ...
    'MaxSCPIter'; ...       % the maximum number of iterations
    'MaxDIRIter'; ...
    'MaxLSIter'; ...
    'MaxTRIter'; ...
    'MaxFTIter'; ...
    'MaxLSDIRIter'; ...
    'MaxEvalFunc'; ...      % the maximum number of evaluate functions
    'TolF'; ...             % tolerances
    'TolX'; ...
    'TolCon'; ...
    'TolDir'; ...           % tolerance for the search direction
    'TolLS' ; ...           % tolerance for the line search
    'Algorithm'; ...        % algorithm
    'Solver'; ...           % solver
    'DIRMethod'; ...        % method for solver sub-problem
    'GlobalStrategy'; ...   % globalization strategy
    'Display'; ...          % display information optional 
    'RunningMode'; ...      % running mode ( quiet | debug )
    'GetInfoEachStep'; ...  % get the information at each step.
    'MaxStepSize'; ...      % maximum and minimum of the step size
    'MinStepSize'; ...      
    'BackTrackingStep'; ... % bactracking step size in line-search
    'InitPenaltyPar'; ...   % initial value of penalty parameter
    'ArmijoPar'; ...        % Armijo parameter in line-search ( c1 )
    'WolfePar' ; ...        % Wolfe parameter in line - search ( c2 )
    'LSInterpPar1'; ...     % Parameter for the interpolation in LS.
    'LSInterpPar2'; ...
    'InitTRRadius'; ...     % initial radius of the trust region
    'PenaltyIncrease'; ...  % increasing penalty parameter.
    'cvxQuiet'; ...         % running mode for cvx solver
    'cvxPrecision'; ...     % precision of cvx solver
    'cvxProbType'; ...      % cvx problem type: gp, sdp, set, ...
    'cvxVarType';  ...      % type of variables in cvx solver
    'cvxExpert';   ...      % cvx expert 
    'cvxSolver';  ...       % the solver using in cvx
    'GradObj'; ...          % compute gradient of objective function
    'JacbCon' ...           % compute Jacobian of equality constraints
};

% declare the field type of the optional variables
fieldtype = { ...
    'integer'; 'integer'; 'integer'; 'integer'; ... % field 1-7.
    'integer'; 'integer'; 'integer'; ... 
    'real'; 'real'; 'real'; 'real'; 'real'; ...     % field 8-11
    'char';  'char'; 'char'; 'char'; ...            % field 12-18
    'char'; 'char'; 'char'; ...
    'real'; 'real'; ...                             % field 19-28
    'real'; 'real'; 'real'; 'real'; ...             
    'real'; 'real'; 'real'; 'real'; ...             
    'logic'; ...                                    % field 29
    'char'; 'char'; 'char'; 'char'; 'char'; ...     % field 30-33.
    'char'; 'char' ...                                          
};

% declare the field range of the optional variables
fieldrange = { ...
    [0, 500]; [0, 500]; [0, 500]; [0, 500]; ....
    [0, 500]; [0, 500]; [0, 500]; [1e-100, 1e0]; ...
    [1e-100, 1e0]; [1e-100, 1e0]; [1e-100, 1e0]; [1e-100, 1e0]; ...
    {'interior-point', 'sqp', 'scp'}; ...
    {'cvx', 'sedumi', 'sdpt3', 'quadprog'}; ...
    {'preconditioning', 'exact', 'quasi-newton'}; ...
    {'line-search', 'trust-region', 'filter', 'full-step'}; ...
    {'off', 'iter', 'deep-iter' }; ...
    {'quiet', 'debug'}; ...
    {'basic', 'medium', 'deep', 'all'}; ...
    [1, 1]; [0, 1]; ...
    [0.1, 0.9]; [0, 1e5]; [1e-5, 1e-1]; ...
    [0.1, 0.9]; [0, 1]; [0, 1]; ...
    [1e-6, 1e5]; [0.1; 1e4]; ...
    {true, false}; {'low', 'default', 'high', 'best', 'medium'}; ...
    {}; {}; {true, false}; {'sedumi', 'sdpt3'}; {'on', 'off'}; ...
    {'auto-diff', 'finite-diff', 'user-provided' } ...
};

% ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
% Copyright 2009 Quoc Tran Dinh and Moritz Diehl.
% See the file COPYING.txt for full copyright information.
% The command 'scp_where' will show where this file is located.
% ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++